version: '3.8'

services:
  app:
    build: .
    ports:
      - "${API_PORT:-3001}:3001"
    volumes:
      - .:/backend  # Adjusted volume mapping to match the new directory structure
    environment:
      NODE_ENV: production
