version: '3.8'

services:
  app:
    build: .
    ports:
      - "${API_PORT:-3001}:${API_PORT:-3001}"
    env_file:
      - .env
    volumes:
      - .:/backend
    environment:
      - API_PORT=${API_PORT:-3001}
