name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.7.2'

    - name: Load environment variables
      run: |
        echo "CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID" >> .env
        echo "CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN" >> .env

    - name: Build & Deploy
      run: |
        cd frontend && npm install && npm run build && npm run deploy 
