name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.7.2'

    - name: Build & Deploy
      run: |
        export CF_ACCOUNT_ID=23807e3ab32b2b792e2b37b7e6232e3c
        wrangler pages deploy ./dist --account-id $CF_ACCOUNT_ID
