name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Change directory to frontend
      run: cd frontend
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.7.2'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Deploy
      run: npm run deploy
